name: mediamtx # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1'
summary: real-time media server and media proxy
description: |
  MediaMTX (formerly rtsp-simple-server) is a ready-to-use and zero-dependency 
  real-time media server and media proxy that allows to publish, 
  read, proxy, record and playback video and audio streams. 
  It has been conceived as a "media router" that routes media streams from one end to the other.

  The configuration file can be edited via /snap/mediamtx/current/mediamtx.yml

website: https://github.com/bluenviron/mediamtx.git

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

adopt-info: mediamtx

parts:
  mediamtx:
    plugin: go
    source: https://github.com/alexdlukens/mediamtx.git
    build-packages: [git, ffmpeg]
    build-snaps: [go]
    override-pull: |
      craftctl default
      GIT_HASH=$(git rev-parse --short HEAD)
      VERSION=1.0.0-snap+${GIT_HASH}
      craftctl set version=$VERSION
    override-build: |
      go mod download
      go generate ./...
      echo "${SNAPCRAFT_PROJECT_VERSION}" > "internal/core/VERSION"
      go build -o $SNAPCRAFT_PART_INSTALL/bin/mediamtx
    override-stage: |
      craftctl default
      cp $CRAFT_PART_BUILD/mediamtx.yml $CRAFT_STAGE/mediamtx.yml
    override-prime: |
      craftctl default
      cp $CRAFT_STAGE/mediamtx.yml $CRAFT_PRIME/mediamtx.yml

apps:
  mediamtx:
    command: bin/mediamtx $SNAP_COMMON/mediamtx.yml
    daemon: simple
    plugs:
      - network
      - network-bind


