name: Build Snap Package

# run on push to snap branch
on:
  schedule:
  - cron: '0 12 * * *' # every day at 12:00 UTC
  push:
    branches:
      - main

jobs:
  build:
    # build snap package
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v3
    - name: Get Git Hash
      id: get-git-hash
      run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Update snapcraft.yaml
      run: |
        sed -i "s/^version: .*/version: '1.0.0+git${GIT_HASH}'/" snap/snapcraft.yaml
    - uses: snapcore/action-build@v1
      id: build-snap
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
    - uses: actions/upload-artifact@v4
      with:
        name: mediamtx
        path: ${{ steps.build-snap.outputs.snap }}
